name: daily_refresh

on:
  schedule:
  - cron: "0 15 * * *"

jobs:
  mlb_refresh:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run MLB Daily
      run: |
        cd MLB
        python refresh.py --daily

  nhl_refresh:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run NHL Daily
      run: |
        cd NHL
        python refresh.py
