name: daily_refresh

on:
  push:
    branches: 
      - master

jobs:
  mlb_refresh:

    runs-on: ubuntu-latest

    steps:
    - name: Change Directory
      run: |
        ls -al
        pwd
        cd ../../MLB
    - name: Run MLB Daily
      run: python refresh.py --daily
